version: "2"

services:
  zion_postgres:
    image: postgres:11.5
    container_name: zion_postgres
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 512mb

  zion_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: zion
    container_name: zion
    command: /bin/bash
    tty: true
    volumes:
      - .:/zion
    ports:
      - "3000:3000"
    depends_on:
      - zion_postgres
    mem_limit: 512mb

volumes:
  postgres:
