version: "2"

services:
  zion_postgres:
    image: postgres:11
    container_name: zion_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - zion-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 512mb

  zion_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: zion
    container_name: zion
    command: ./script/docker-entrypoint.sh
    tty: true
    environment:
      LOAD_SCHEMA: true # it should be true when you first setup the app
    volumes:
      - .:/zion
      - zion-gems:/gems
      - bashhistory:/commandhistory
    ports:
      - "3000:3000"
    depends_on:
      - zion_postgres
    mem_limit: 512mb

volumes:
  postgres:
  zion-gems:
  zion-data:
  bashhistory: