# avalilable envs: production, development and test

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('ZION_DATABASE_HOST', 'zion_postgres') %>

development:
  <<: *default
  database: zion_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: zion_test
  username: postgres
  password: postgres
