# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9734d2c93dc16bedf2625ffaaaf4ffd5c56ca145aea60c0cfe680cc15c9e87dd17e89fa2e30b09d552fd670bc65e349ffa59e9c244451ede592f572987a5f232
  smtp_address: <%= ENV["SMTP_ADDRESS_DEV"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN_DEV"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD_DEV"] %>
  smtp_port: <%= ENV["SMTP_PORT_DEV"] %>
  smtp_username: <%= ENV["SMTP_USERNAME_DEV"] %>

test:
  secret_key_base: 2b6cc344c2e3bb44aaeb8e1e09c64e905929febc553382503d92c73eb499a73af0f937c760f06c704fcb2904ef60e7474fc60b63150607cae258a6867792e959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
